# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cphh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
