# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:37
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cphh', '0003_auto_20170501_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='model_pic',
            field=smartfields.fields.ImageField(upload_to=b''),
        ),
    ]
