# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cphh', '0004_auto_20170501_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='moderated',
            field=smartfields.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
